// This file will be auto-generated by Supabase CLI
// Run: supabase gen types typescript --project-id YOUR_PROJECT_ID > lib/database.types.ts

export interface Database {
  public: {
    Tables: {
      hotels: {
        Row: {
          id: string;
          name: string;
          brand: string | null;
          address: string;
          city: string;
          state: string;
          zip: string;
          latitude: number;
          longitude: number;
          phone: string | null;
          website: string | null;
          star_rating: number | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          brand?: string | null;
          address: string;
          city: string;
          state: string;
          zip: string;
          latitude: number;
          longitude: number;
          phone?: string | null;
          website?: string | null;
          star_rating?: number | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          brand?: string | null;
          address?: string;
          city?: string;
          state?: string;
          zip?: string;
          latitude?: number;
          longitude?: number;
          phone?: string | null;
          website?: string | null;
          star_rating?: number | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      bars: {
        Row: {
          id: string;
          hotel_id: string;
          name: string | null;
          type: 'bar' | 'lounge' | 'rooftop' | 'poolside' | 'restaurant_bar';
          serves_food: boolean;
          hours: Json;
          happy_hour: Json | null;
          features: string[];
          phone_number: string | null;
          description: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          hotel_id: string;
          name?: string | null;
          type: 'bar' | 'lounge' | 'rooftop' | 'poolside' | 'restaurant_bar';
          serves_food?: boolean;
          hours: Json;
          happy_hour?: Json | null;
          features?: string[];
          phone_number?: string | null;
          description?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          hotel_id?: string;
          name?: string | null;
          type?: 'bar' | 'lounge' | 'rooftop' | 'poolside' | 'restaurant_bar';
          serves_food?: boolean;
          hours?: Json;
          happy_hour?: Json | null;
          features?: string[];
          phone_number?: string | null;
          description?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      user_favorites: {
        Row: {
          id: string;
          user_id: string;
          hotel_id: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          hotel_id: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          hotel_id?: string;
          created_at?: string;
        };
      };
      search_history: {
        Row: {
          id: string;
          user_id: string;
          query: string;
          search_mode: string;
          filters: Json;
          searched_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          query: string;
          search_mode: string;
          filters: Json;
          searched_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          query?: string;
          search_mode?: string;
          filters?: Json;
          searched_at?: string;
        };
      };
      profiles: {
        Row: {
          id: string;
          user_id: string;
          first_name: string | null;
          last_name: string | null;
          avatar_url: string | null;
          preferences: Json | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          first_name?: string | null;
          last_name?: string | null;
          avatar_url?: string | null;
          preferences?: Json | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          first_name?: string | null;
          last_name?: string | null;
          avatar_url?: string | null;
          preferences?: Json | null;
          created_at?: string;
          updated_at?: string;
        };
      };
    };
    Views: {
      [_ in never]: never;
    };
    Functions: {
      nearby_hotels: {
        Args: {
          lat: number;
          lng: number;
          radius_miles?: number;
        };
        Returns: {
          id: string;
          name: string;
          brand: string | null;
          address: string;
          city: string;
          state: string;
          distance_miles: number;
        }[];
      };
      search_hotels_with_bars: {
        Args: {
          search_query: string;
          lat?: number;
          lng?: number;
          radius_miles?: number;
          bar_filters?: Json;
        };
        Returns: {
          id: string;
          name: string;
          brand: string | null;
          city: string;
          state: string;
          latitude: number;
          longitude: number;
          distance_miles: number | null;
          bar_count: number;
        }[];
      };
    };
    Enums: {
      bar_type: 'bar' | 'lounge' | 'rooftop' | 'poolside' | 'restaurant_bar';
    };
  };
}

type Json = string | number | boolean | null | { [key: string]: Json } | Json[];