import { Hotel, Bar } from './types';

export const mockHotels: Hotel[] = [
  {
    id: '1',
    name: 'The Plaza Hotel',
    brand: 'Fairmont',
    address: '768 5th Ave',
    city: 'New York',
    state: 'NY',
    zip: '10019',
    latitude: 40.7648,
    longitude: -73.9808,
    phone: '(212) 759-3000',
    starRating: 5,
  },
  {
    id: '2',
    name: 'Hotel del Coronado',
    brand: 'Curio Collection',
    address: '1500 Orange Ave',
    city: 'Coronado',
    state: 'CA',
    zip: '92118',
    latitude: 32.6814,
    longitude: -117.1751,
    phone: '(619) 435-6611',
    starRating: 4,
  },
  {
    id: '3',
    name: 'The Chicago Hotel',
    brand: 'Marriott',
    address: '505 N Michigan Ave',
    city: 'Chicago',
    state: 'IL',
    zip: '60611',
    latitude: 41.8914,
    longitude: -87.6256,
    phone: '(312) 944-4100',
    starRating: 4,
  },
  {
    id: '4',
    name: 'Sunset Tower Hotel',
    brand: 'Independent',
    address: '8358 Sunset Blvd',
    city: 'West Hollywood',
    state: 'CA',
    zip: '90069',
    latitude: 34.0969,
    longitude: -118.3781,
    phone: '(323) 654-7100',
    starRating: 5,
  },
  {
    id: '5',
    name: 'The Roosevelt Hotel',
    brand: 'Waldorf Astoria',
    address: '45 E 45th St',
    city: 'New York',
    state: 'NY',
    zip: '10017',
    latitude: 40.7505,
    longitude: -73.9776,
    phone: '(212) 661-9600',
    starRating: 4,
  },
  {
    id: '6',
    name: 'Beverly Hills Hotel',
    brand: 'Dorchester Collection',
    address: '9641 Sunset Blvd',
    city: 'Beverly Hills',
    state: 'CA',
    zip: '90210',
    latitude: 34.0901,
    longitude: -118.4065,
    phone: '(310) 276-2251',
    starRating: 5,
  }
];

export const mockBars: Bar[] = [
  {
    id: 'bar-1',
    hotelId: '1',
    name: 'The Oak Room',
    type: 'lounge',
    servesFood: true,
    hours: {
      mon: { open: '16:00', close: '24:00' },
      tue: { open: '16:00', close: '24:00' },
      wed: { open: '16:00', close: '24:00' },
      thu: { open: '16:00', close: '01:00' },
      fri: { open: '16:00', close: '02:00' },
      sat: { open: '14:00', close: '02:00' },
      sun: { open: '14:00', close: '23:00' },
    },
    happyHour: {
      days: ['mon', 'tue', 'wed', 'thu', 'fri'],
      startTime: '16:00',
      endTime: '19:00',
    },
    features: ['live_music', 'outdoor_seating', 'craft_cocktails'],
    description: 'Elegant cocktail lounge with live jazz and gourmet small plates.',
  },
  {
    id: 'bar-2',
    hotelId: '2',
    name: 'Babcock & Story Bar',
    type: 'bar',
    servesFood: true,
    hours: {
      mon: { open: '15:00', close: '23:00' },
      tue: { open: '15:00', close: '23:00' },
      wed: { open: '15:00', close: '23:00' },
      thu: { open: '15:00', close: '24:00' },
      fri: { open: '15:00', close: '01:00' },
      sat: { open: '12:00', close: '01:00' },
      sun: { open: '12:00', close: '23:00' },
    },
    happyHour: {
      days: ['mon', 'tue', 'wed', 'thu', 'fri'],
      startTime: '15:00',
      endTime: '18:00',
    },
    features: ['outdoor_seating', 'ocean_view', 'craft_cocktails'],
    description: 'Historic beachfront bar with ocean views and craft cocktails.',
  },
  {
    id: 'bar-3',
    hotelId: '3',
    name: 'Altitude Sky Lounge',
    type: 'rooftop',
    servesFood: true,
    hours: {
      mon: { open: '17:00', close: '24:00' },
      tue: { open: '17:00', close: '24:00' },
      wed: { open: '17:00', close: '24:00' },
      thu: { open: '17:00', close: '01:00' },
      fri: { open: '17:00', close: '02:00' },
      sat: { open: '16:00', close: '02:00' },
      sun: { open: '16:00', close: '24:00' },
    },
    happyHour: {
      days: ['mon', 'tue', 'wed', 'thu'],
      startTime: '17:00',
      endTime: '19:00',
    },
    features: ['rooftop', 'city_views', 'craft_cocktails', 'outdoor_seating'],
    description: 'Rooftop lounge with stunning city skyline views.',
  },
  {
    id: 'bar-4',
    hotelId: '4',
    name: 'Tower Bar',
    type: 'lounge',
    servesFood: true,
    hours: {
      mon: { open: '18:00', close: '01:00' },
      tue: { open: '18:00', close: '01:00' },
      wed: { open: '18:00', close: '01:00' },
      thu: { open: '18:00', close: '01:00' },
      fri: { open: '18:00', close: '02:00' },
      sat: { open: '18:00', close: '02:00' },
      sun: { open: '18:00', close: '24:00' },
    },
    features: ['live_music', 'celebrity_spotting', 'craft_cocktails'],
    description: 'Iconic Hollywood lounge frequented by celebrities.',
  },
  {
    id: 'bar-5',
    hotelId: '5',
    name: 'Madison Club Lounge',
    type: 'lounge',
    servesFood: true,
    hours: {
      mon: { open: '16:00', close: '24:00' },
      tue: { open: '16:00', close: '24:00' },
      wed: { open: '16:00', close: '24:00' },
      thu: { open: '16:00', close: '01:00' },
      fri: { open: '16:00', close: '02:00' },
      sat: { open: '14:00', close: '02:00' },
      sun: { open: '14:00', close: '23:00' },
    },
    happyHour: {
      days: ['mon', 'tue', 'wed', 'thu', 'fri'],
      startTime: '16:00',
      endTime: '19:00',
    },
    features: ['live_music', 'piano_bar', 'craft_cocktails'],
    description: 'Classic New York lounge with live piano and premium cocktails.',
  },
  {
    id: 'bar-6',
    hotelId: '6',
    name: 'Polo Lounge',
    type: 'lounge',
    servesFood: true,
    hours: {
      mon: { open: '07:00', close: '01:00' },
      tue: { open: '07:00', close: '01:00' },
      wed: { open: '07:00', close: '01:00' },
      thu: { open: '07:00', close: '01:00' },
      fri: { open: '07:00', close: '02:00' },
      sat: { open: '07:00', close: '02:00' },
      sun: { open: '07:00', close: '01:00' },
    },
    features: ['outdoor_seating', 'celebrity_spotting', 'classic_cocktails'],
    description: 'Legendary Beverly Hills meeting spot for Hollywood elite.',
  }
];